# Generated by Django 5.2.7 on 2025-10-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='noticias/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
